#version 450
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
layout(local_size_x = 1) in;
struct B { f16vec2 dm; uint8_t arr[8]; uint16_t s[4]; };
layout(set=0, binding=0) readonly buffer A { B blk[]; } inbuf;
layout(set=0, binding=1) buffer O { float outv; } outbuf;
void main() {
    outbuf.outv = float(uint(inbuf.blk[0].s[0]));
}
